-- SQL
DROP TABLE IF EXISTS P11_Equipe;
DROP TABLE IF EXISTS P11_Membre;
DROP TABLE IF EXISTS P11_Joue;
DROP TABLE IF EXISTS P11_Selectionne;

CREATE TABLE P11_Equipe (
  equipe_id SERIAL PRIMARY KEY,
  equipe_nom VARCHAR(25) NOT NULL,
  equipe_fed VARCHAR (50) NOT NULL,
  equipe_cont VARCHAR (50) NOT NULL
);
 
CREATE TABLE P11_Membre (
  membre_id SERIAL PRIMARY KEY,
  membre_nom VARCHAR (50) NOT NULL,
  membre_prenom VARCHAR(50) NOT NULL,
  membre_statut VARCHAR(15) CHECK (membre_statut IN ('Joueur', 'Selectionneur')),
  membre_poste VARCHAR (30) CHECK (membre_poste IN ('Gardien', 'Defenseur', 'Milieu', 'Attaquant')),
  membre_num INT,
  equipe_id INT,
  FOREIGN KEY (equipe_id) REFERENCES P11_Equipe(equipe_id)
);
 
CREATE TABLE P11_Joue (
  equipe_id INT NOT NULL,
  membre_id INT NOT NULL,
  FOREIGN KEY (equipe_id) REFERENCES P11_Equipe(equipe_id),
  FOREIGN KEY (membre_id) REFERENCES P11_Membre(membre_id),
  PRIMARY KEY (equipe_id, membre_id)
);

CREATE TABLE P11_Selectionne (
  equipe_id INT NOT NULL,
  membre_id INT NOT NULL,
  FOREIGN KEY (equipe_id) REFERENCES P11_Equipe(equipe_id),
  FOREIGN KEY (membre_id) REFERENCES P11_Membre(membre_id),
  PRIMARY KEY (equipe_id, membre_id)
);

INSERT INTO P11_Equipe (equipe_nom, equipe_fed, equipe_cont) VALUES
  ('Bresil', 'Federation bresilienne de football','Amerique du Sud'),
  ('France', 'Federation française de football', 'Europe'),
  ('Maroc', 'Federation marocaine de football','Afique'),
  ('Espagne', 'Federation espagnole de football','Europe');

INSERT INTO P11_Membre (membre_nom, membre_prenom, membre_statut, membre_poste, membre_num, equipe_id) VALUES
  ('Bacchi', 'Adenor Leonardo', 'Selectionneur', NULL, NULL, 1),
  ('Becker', 'Alisson', 'Joueur', 'Gardien', 1, 1),
  ('Moraes', 'Ederson', 'Joueur', 'Gardien', 23, 1),
  ('Pereira da Silva', 'Weverton', 'Joueur', 'Gardien', 12, 1),
  ('Alves', 'Daniel', 'Joueur', 'Defenseur', 13, 1),
  ('Silva', 'Thiago', 'Joueur', 'Defenseur', 3, 1),
  ('Correa', 'Marcos', 'Joueur', 'Defenseur', 4, 1),
  ('Danilo', 'Luiz', 'Joueur', 'Defenseur', 2, 1),
  ('Lobo Silva', 'Alex Sandro', 'Joueur', 'Defenseur', 6, 1),
  ('Militao', 'Eder', 'Joueur', 'Defenseur', 14, 1),
  ('Bremer', 'Gleison', 'Joueur', 'Defenseur', 24, 1),
  ('Telles', 'Alex', 'Joueur', 'Defenseur', 16, 1),
  ('Rodrigues de Paula Santos', 'Frederico', 'Joueur', 'Milieu', 8, 1),
  ('Casimiro', 'Carlos Henrique', 'Joueur', 'Milieu', 5, 1),
  ('Ribeiro', 'Everton', 'Joueur', 'Milieu', 22, 1),
  ('Paqueta', 'Lucas', 'Joueur', 'Milieu', 7, 1),
  ('Tavares', 'Fabio Henrique', 'Joueur', 'Milieu', 15, 1),
  ('Guimaraes', 'Bruno', 'Joueur', 'Milieu', 17, 1),
  ('Dos Santos', 'Pedro', 'Joueur', 'Attaquant', 25, 1),
  ('Da Silva Santos', 'Neymar', 'Joueur', 'Attaquant', 10, 1),
  ('Jesus', 'Gabriel', 'Joueur', 'Attaquant', 18, 1),
  ('De Andrade', 'Richarlison', 'Joueur', 'Attaquant', 9, 1),
  ('Vinicius', 'Paixao de Oliveira', 'Joueur', 'Attaquant', 20, 1),
  ('Dias Belloli', 'Raphael', 'Joueur', 'Attaquant', 11, 1),
  ('Silva de Goes', 'Rodrygo', 'Joueur', 'Attaquant', 21, 1),
  ('Martinelli', 'Gabriel', 'Joueur', 'Attaquant', 26, 1),
  ('Matheus dos santos', 'Antony', 'Joueur', 'Attaquant', 19, 1),

  ('Deschamps','Didier','Selectionneur', NULL, NULL, 2),
  ('Areola','Alphonse','Joueur','Gardien', 23, 2),
  ('Lloris','Hugo','Joueur','Gardien', 1, 2),
  ('Mandanda','Steve','Joueur','Gardien', 16, 2),
  ('Hernandez','Lucas','Joueur','Defenseur', 21, 2),
  ('Hernandez','Theo','Joueur','Defenseur', 22, 2),
  ('Disasi','Axel','Joueur','Defenseur', 3, 2),
  ('Konate','Ibrahima','Joueur','Defenseur', 24, 2),
  ('Kounde','Jules','Joueur','Defenseur', 5, 2),
  ('Pavard','Benjamin','Joueur','Defenseur', 2, 2),
  ('Saliba','William','Joueur','Defenseur', 17, 2),
  ('Upamecano','Dayot','Joueur','Defenseur', 18, 2),
  ('Varane','Raphael','Joueur','Defenseur', 4, 2),
  ('Fofana','Youssouf','Joueur','Milieu', 13, 2),
  ('Camavinga','Eduardo','Joueur','Milieu', 25, 2),
  ('Guendouzi','Matteo','Joueur','Milieu', 6, 2),
  ('Rabiot','Adrien','Joueur','Milieu', 14, 2),
  ('Tchouameni','Aurelien','Joueur','Milieu', 8, 2),
  ('Veretout','Jordan','Joueur','Milieu', 15, 2),
  ('Benzema','Karim','Joueur','Attaquant', 19, 2),
  ('Coman','Kingsley','Joueur','Attaquant', 20, 2),
  ('Dembele','Ousmane','Joueur','Attaquant', 11, 2),
  ('Griezmann','Antoine','Joueur','Attaquant', 7, 2),
  ('Giroud','Olivier','Joueur','Attaquant', 9, 2),
  ('Mbappe','Kylian','Joueur','Attaquant', 10, 2),
  ('Nkunku','Christopher','Joueur','Attaquant', 12, 2),
  ('Thuram','Marcus','Joueur','Attaquant', 26, 2),

  ('Regragui','Walid','Selectionneur',NULL,NULL,3),
  ('Bounou','Yassine','Joueur','Gardien', 1, 3),
  ('Tagnaouti','Ahmed','Joueur','Gardien',22,3),
  ('El Kajoui','Munir','Joueur','Gardien',12,3),
  ('Aguerd','Nayef','Joueur','Defenseur',5,3),
  ('Saïss','Romain','Joueur','Defenseur',6,3),
  ('Dari','Achraf','Joueur','Defenseur',20,3),
  ('El Yamiq','Jawad','Joueur','Defenseur',18,3),
  ('Benoun','Badr','Joueur','Defenseur',24,3),
  ('Attiyat Allah','Yahia','Joueur','Defenseur',25,3),
  ('Mazraoui','Noussair','Joueur','Defenseur',3,3),
  ('Hakimi','Achraf','Joueur','Defenseur',2,3),
  ('Amrabat','Sofyan','Joueur','Milieu',4,3),
  ('Jabrane','Yahya','Joueur','Milieu',26,3),
  ('Ounahi','Azzedine','Joueur','Milieu',8,3),
  ('Ziyech','Hakim','Joueur','Milieu',7,3),
  ('Amallah','Selim','Joueur','Milieu',15,3),
  ('El Khannouss','Bilal','Joueur','Milieu',23,3),
  ('Sabiri','Abdelhamid','Joueur','Milieu',11,3),
  ('Ez Abde','Abdessamad','Joueur','Attaquant',16,3),
  ('Boufal','Sofiane','Joueur','Attaquant',17,3),
  ('Chair','Ilias','Joueur','Attaquant',13,3),
  ('Zaroury','Anass','Joueur','Attaquant',10,3),
  ('Aboukhlal','Zakaria','Joueur','Attaquant',14,3),
  ('En-Nesyri','Youssef','Joueur','Attaquant',19,3),
  ('Hamdallah','Abderrazak','Joueur','Attaquant',9,3),
  ('Cheddira','Walid','Joueur','Attaquant',21,3),


  ('Enrique','Luis','Selectionneur', NULL, NULL, 4),
  ('Simon', 'Unai','Joueur', 'Gardien', 23, 4),
  ('Sanchez','Robert','Joueur','Gardien', 1, 4),
  ('Raya','David','Joueur','Gardien', 13, 4), 
  ('Carvajal','Dani','Joueur','Defenseur', 20, 4),
  ('Azpilicueta','Cesar','Joueur','Defenseur', 2, 4),
  ('Garcia','Eric','Joueur','Defenseur', 3, 4),
  ('Guillamon','Hugo','Joueur','Defenseur', 15, 4),
  ('Torres','Pau','Joueur','Defenseur', 4, 4),
  ('Laporte','Aymeric','Joueur','Defenseur', 24, 4),
  ('Alba','Jordi','Joueur','Defenseur', 18, 4),
  ('Gaya','Jose','Joueur','Defenseur', 14, 4),
  ('Busquets','Sergio','Joueur','Milieu',5,4),
  ('Llorente','Marcos','Joueur','Milieu',6,4),
  ('Koke','Jorge','Joueur','Milieu',8,4),
  ('Rodri','Hernández','Joueur','Milieu',16,4),
  ('Pedri','González','Joueur','Milieu',26,4),
  ('Torres','Ferran','Joueur','Milieu',11,4),
  ('Sarabia','Pablo','Joueur','Milieu',22,4),
  ('Soler','Carlos','Joueur','Milieu',19,4),
  ('Gavi','Pablo','Joueur','Milieu',9,4),
  ('Morata', 'Alvaro', 'Joueur', 'Attaquant', 7, 4),
  ('Asensio', 'Marco', 'Joueur', 'Attaquant', 10, 4),
  ('Olmo', 'Dani','Joueur','Attaquant', 21, 4),
  ('Williams', 'Nico', 'Joueur', 'Attaquant', 12, 4),
  ('Pino', 'Yeremi', 'Joueur', 'Attaquant', 17, 4),
  ('Fati', 'Ansu', 'Joueur', 'Attaquant', 25, 4);

--On utilise des sous-requête pour récupérer l'identifiant des Selectionneurs

INSERT INTO P11_Selectionne VALUES
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_nom = 'Bacchi')),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_nom = 'Deschamps')),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_nom = 'Regragui')),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_nom = 'Enrique'));

--On utilise des sous-requête pour récupérer l'identifiant des Joueurs

INSERT INTO P11_Joue VALUES
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 1 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 2 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 3 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 4 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 5 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 6 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 7 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 8 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 9 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 10 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 11 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 12 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 13 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 14 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 15 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 16 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 17 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 18 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 19 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 20 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 21 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 22 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 23 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 24 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 25 AND equipe_id =1)),
  (1, (SELECT membre_id FROM P11_Membre WHERE membre_num = 26 AND equipe_id =1)),

  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 1 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 2 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 3 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 4 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 5 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 6 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 7 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 8 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 9 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 10 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 11 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 12 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 13 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 14 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 15 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 16 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 17 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 18 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 19 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 20 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 21 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 22 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 23 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 24 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 25 AND equipe_id =2)),
  (2, (SELECT membre_id FROM P11_Membre WHERE membre_num = 26 AND equipe_id =2)),

  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 1 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 2 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 3 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 4 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 5 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 6 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 7 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 8 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 9 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 10 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 11 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 12 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 13 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 14 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 15 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 16 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 17 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 18 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 19 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 20 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 21 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 22 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 23 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 24 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 25 AND equipe_id =3)),
  (3, (SELECT membre_id FROM P11_Membre WHERE membre_num = 26 AND equipe_id =3)),

  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 1 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 2 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 3 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 4 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 5 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 6 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 7 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 8 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 9 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 10 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 11 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 12 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 13 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 14 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 15 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 16 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 17 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 18 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 19 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 20 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 21 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 22 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 23 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 24 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 25 AND equipe_id =4)),
  (4, (SELECT membre_id FROM P11_Membre WHERE membre_num = 26 AND equipe_id =4));
